steps:

# Install node packages
- name: node
  entrypoint: npm
  args: ['install']
  dir: 'angular-demo-app'

# Build productive files
- name: node
  entrypoint: npm
  args: ['run', 'build', '--prod']
  dir: 'angular-demo-app'

# Deploy to google cloud app engine
- name: "gcr.io/cloud-builders/gcloud"
  args: ['app', 'deploy', '--version=prod']
  dir: 'angular-demo-app'